//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_files
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string content_type { get; set; }
        public byte[] data { get; set; }
        public int user_id { get; set; }
        public bool checked_file { get; set; }
    
        public virtual client_data client_data { get; set; }
    }
}
